<?php
    require_once('../tcpdf/tcpdf.php');
    include '../db_conn.php';

    $invoiceNo = $_GET['invoiceNo']; // Get the invoice number from the URL
    $invoiceNo = mysqli_real_escape_string($conn, $invoiceNo);

    // Fetch the main invoice data
    $invoice_sql = "SELECT r.receiptID, r.date, r.totalAmount, c.name, c.email, c.address, p.method, a.username FROM receipt r JOIN customer c ON r.icNo = c.icNo JOIN payment_method p ON r.paymentMethodID = p.paymentMethodID JOIN admin a ON r.id = a.id WHERE r.receiptID = ?";
    $stmt = $conn->prepare($invoice_sql);
    $stmt->bind_param("i", $invoiceNo);

    if ($stmt->execute()) {
        $result = $stmt->get_result();
        if ($result->num_rows > 0) {
            // Get the invoice data
            $invoiceData = $result->fetch_assoc();

            //Change date format
            $dateOriginal = $invoiceData['date'];
            $dateObject = DateTime::createFromFormat('Y-m-d', $dateOriginal);
            $dateFormatted = $dateObject->format('d-m-Y');

            $totalAmount = $invoiceData['totalAmount'];
            $customerName = $invoiceData['name'];
            $email = $invoiceData['email'];
            $address = $invoiceData['address'];
            $paymentMethod = $invoiceData['method'];
            $adminName = $invoiceData['username'];
        } else {
            echo "No invoice found with that ID.";
            // Handle the case where no invoice is found
        }
    } else {
        echo "Error executing query: " . $conn->error;
        // Handle the case where the query did not execute properly
    }


    // Fetch line items or other related data
    $lineItemsStmt = $conn->prepare("SELECT * FROM receipt_items WHERE receiptID = ?");
    $lineItemsStmt->bind_param("i", $invoiceNo);
    $lineItemsStmt->execute();
    $lineItemsResult = $lineItemsStmt->get_result();
    $lineItems = []; // Initialize as an empty array

    while ($item = $lineItemsResult->fetch_assoc()) {
        $lineItems[] = $item; // Store each item in the array
    }

    // create new PDF document
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Furry Friends Health Center');
$pdf->SetTitle('Invoice');
$pdf->SetSubject('Customer Invoice');
$pdf->SetKeywords('TCPDF, PDF, invoice');

// remove default header/footer
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);

// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, 10, PDF_MARGIN_RIGHT);
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// add a page
$pdf->AddPage();

//Generate html
$html = <<<EOD
<table cellpadding="5" cellspacing="0" border="0" style="width: 100%;">
    <tr>
        <td style="width: 50%;">
            <img src="../Profile Picture/Garfield-and-Odie.jpg" alt="Logo" style="width: 60px; height: 60px;">
            <h3>Furry Friends Health Center</h3>
            <p>1234 Tailwag Terrace<br>Purrville, Petlandia, 98765<br>Phone: (555) 123-4567</p>
        </td>
        <td style="width: 50%;">
            <table cellpadding="5" cellspacing="0" border="1" style="width: 100%; border-collapse: collapse;">
                <tr>
                    <td style="width: 50%; font-weight: bold;">Invoice No</td>
                    <td style="width: 50%;">{$invoiceData['receiptID']}</td>
                </tr>
                <tr>
                    <td style="font-weight: bold;">Date</td>
                    <td>{$dateFormatted}</td>
                </tr>
                <tr>
                    <td style="font-weight: bold;">Generated By</td>
                    <td>{$adminName}</td>
                </tr>
                <tr>
                    <td style="font-weight: bold;">Payment Method</td>
                    <td>{$paymentMethod}</td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td colspan="2" style="text-align: right;">
            <b>Bill To:</b> <br>
            {$customerName}<br>
            {$email}<br>
            {$address}
        </td>
    </tr>
    <tr>
        <td colspan="2">
            <table cellpadding="5" cellspacing="0" border="1" style="width: 100%; border-collapse: collapse;">
                <thead>
                    <tr>
                        <th style="width: 80%; background-color: #eee;">Description</th>
                        <th style="width: 20%; background-color: #eee;">Amount (RM)</th>
                    </tr>
                </thead>
                <tbody>
EOD;

foreach ($lineItems as $item) {
    $html .= "<tr>
                <td>{$item['itemDescription']}</td>
                <td style=\"text-align: right;\">{$item['itemPrice']}</td>
              </tr>";
}

$html .= <<<EOD
                </tbody>
                <tfoot>
                    <tr>
                        <td style="text-align: right; font-weight: bold;">Total Amount: RM</td>
                        <td style="text-align: right; font-weight: bold;">{$totalAmount}</td>
                    </tr>
                </tfoot>
            </table>
        </td>
    </tr>
</table>
EOD;

$pdf->writeHTML($html, true, false, true, false, '');
$pdf->Output('invoice.pdf', 'I');

// output the HTML content
$pdf->writeHTML($html, true, false, true, false, '');

// Output the PDF
$pdf->Output('invoice.pdf', 'I');

?>
