<?php
    session_start();

    //Include database
    include '../db_conn.php';

    // Check if the user is not logged in
    if (!isset($_SESSION["userID"])) {
        header("Location: ../Admin Login Page/");
        exit();
    }

    // Retrieve the username from the session
    $username = isset($_SESSION["username"]) ? $_SESSION["username"] : "";

    // The user is logged in, continue displaying the homepage
    include '../sidebar.php';

    //Bind dropdown from database
    $paymentMethod_query = "SELECT * FROM payment_method";
    $paymentMethod_result = $conn->query($paymentMethod_query);

    // SQL to get the highest receiptID
    $invoiceNo_sql = "SELECT MAX(receiptID) as lastReceiptID FROM receipt";
    $result = $conn->query($invoiceNo_sql);
    if ($result->num_rows > 0) {
        // Get the last receiptID
        $row = $result->fetch_assoc();
        $lastReceiptID = $row['lastReceiptID'] + 1;
    } else {
        echo "0 results";
    }

    // Check if the 'icNo' is set in the URL query parameters
    if (isset($_GET['icNo'])) {
        $icNo = $_GET['icNo'];
        $icNo = mysqli_real_escape_string($conn, $icNo);

        $stmt = $conn->prepare("SELECT name FROM customer WHERE icNo = ?");
        $stmt->bind_param("s", $icNo);
        $stmt->execute();
        $result = $stmt->get_result();

        if ($row = $result->fetch_assoc()) {
            // Now you have the customer's name, and you can use it as needed
            $customerName = $row['name'];
        }else{
            $customerName = "Not found";
        }

        $stmt->close();
    }

    $conn->close();
?>

        <div class="flex-grow-1 p-3" style="overflow-y: auto; margin-top: -20px;">
            <div class="container-fluid">
                <div class="row">
                    <!-- Ensure the main content area takes the remaining space after the 280px sidebar -->
                    <div class="col-md-9 col-lg-10 px-md-4">

                        <h1 class="display-5 fw-bold text-body-emphasis">Invoice</h1>

                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="../Admin Homepage/homepage.php">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Invoice</li>
                            </ol>
                        </nav> 

                        <form id="invoiceForm" method="post">
                            <div class="card mb-3 mt-4" style="max-width: 1200px; margin-left: 30px;">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-md-6 mb-3">
                                            <div style="width: 100px; height: 100px;  display: flex; justify-content: center; align-items: center;">
                                                <img src="../Profile Picture/Garfield-and-Odie.png" alt="Company Logo" style="width: auto; height: 100%;">
                                            </div>
                                            <h3 class="mt-2">Furry Friends Health Center</h3>
                                            <p>Furry Friends Health Center
                                                <br />
                                                1234 Tailwag Terrace
                                                <br />
                                                Purrville, Petlandia, 98765
                                                <br />
                                                Phone: (555) 123-4567
                                            </p>
                                        </div>
                                        <div class="col-md-6 mb-3">
                                            <form>
                                                <div class="mb-3">
                                                    <label for="invoiceNo" class="form-label">Invoice No:</label>
                                                    <input type="text" class="form-control" id="invoiceNo" value="<?php echo htmlspecialchars($lastReceiptID); ?>" disabled readonly>
                                                </div>
                                                <div class="mb-3">
                                                    <label for="invoiceDate" class="form-label">Date:</label>
                                                    <input type="text" class="form-control" id="invoiceDate" disabled readonly>
                                                </div>
                                                <div class="mb-3">
                                                    <label for="generatedBy" class="form-label">Generated By:</label>
                                                    <input type="text" class="form-control" id="generatedBy" value="<?php echo htmlspecialchars($username); ?>" disabled readonly>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                    <div class="row border-top pt-3">
                                        <div class="col-md-6 mb-3">
                                            <label for="billTo" class="form-label">Bill To:</label>
                                            <input type="text" class="form-control" id="billTo" value="<?php echo htmlspecialchars($customerName); ?>" disabled readonly>
                                        </div>
                                        <div class="col-md-6 mb-3">
                                            <label for="paymentMethod" class="form-label">Payment Method:</label>
                                            <select class="form-select" id="paymentMethod">
                                                <option selected>Choose...</option>
                                                <?php
                                                    if($paymentMethod_result->num_rows > 0){
                                                        while($row = $paymentMethod_result->fetch_assoc()){
                                                            echo '<option value="'.$row['paymentMethodID'].'">'.$row['method'].'</option>';
                                                        }
                                                    }else{
                                                        echo '<option>No payment method found</option>';
                                                    }
                                                ?>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-12">
                                            <table class="table" id="lineItems">
                                                <thead>
                                                    <tr>
                                                        <th scope="col">Description</th>
                                                        <th scope="col">Amount (RM)</th>
                                                        <th scope="col">Action</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr class="line-item">
                                                        <td><input type="text" class="form-control" name="description[]" required></td>
                                                        <td><input type="text" class="form-control line-item-amount" name="amount[]" oninput="updateTotalAmount()"></td>
                                                        <td><button type="button" class="btn btn-danger remove-line-item"><i class="bi bi-trash3"></i></button></td>
                                                    </tr>
                                                    <!-- Additional rows will be added here -->
                                                </tbody>
                                            </table>
                                            <button type="button" class="btn btn-link" id="addLineItem">+ Add another line item</button>
                                        </div>
                                    </div>

                                    <div class="row justify-content-end mt-3">
                                        <div class="col-md-3">
                                            <h4>Total RM: <p id="totalAmount">0.00</p></h4>
                                        </div>
                                    </div>

                                </div>
                            </div>
                            <div class="mb-3 text-center" style="margin-top: 50px">
                                <a id="backBtn" class="btn btn-secondary me-3" onclick="goBackInvoice()">Back</a>
                                <a id="saveBtn" class="btn btn-primary me-3">Save</a>
                                <a id="printBtn" href="../Admin Invoice Page/generate_pdf.php?invoiceNo=<?php echo $lastReceiptID; ?>" class="btn btn-primary me-3" target="_blank">Print</a>
                            </div>
                        </form>
                        
                        <!--Success/Error Message Modal Box-->
                        <div class="modal fade" id="responseModal" tabindex="-1" aria-labelledby="responseModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="responseModalLabel">Message</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <!-- The AJAX response message will be displayed here -->
                                    </div>
                                </div>
                            </div>
                        </div>
                    
                    </div>
                </div>
            </div>
        </div>

</main>
    </body>    
</html>